version: '3.8'

services:
  ca:
    build: .
    image: private-root-ca:latest
    container_name: private-root-ca
    command: sleep infinity
    environment:
      # Set to 'true' to strictly enforce CN requirements and block generic test certs
      - PKI_PROD_MODE=false
    volumes:
      # Main output directory for keys and certs
      - ./output:/ca/output
      
      # Batch Processing: Bring Your Own Intermediate Keys
      - ./int-keys:/ca/int-keys:ro
      
      # Root Key Processing: Optional explicit root key
      - ./host_root.key:/root.key:ro
      
      # Optional: Override all default cert intervals config
      # - ./pki-config.json:/ca/pki-config.json:ro
    
    # Run as a specific UID/GID so files generated on the host 
    # belong to your user naturally.
    # user: "1000:1000"
